fix: disconnect trigger an error NoVC has been set
This commit fixes the issue when the bot errors out and think that it's still in the voice channel thus creating this error.
RangeError: No voice channel has been set.
    at Object.connect (/root/discord/DiscordMusic/node_modules/erela.js/dist/structures/Player.js:146:19)
    at SlashCommand.run (/root/discord/DiscordMusic/commands/slash/play.js:26:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Signed-off-by: Darren <git@darrennathanael.com>
Fixes: https://github.com/SudhanPlayz/Discord-MusicBot/issues/696